apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: n8n-tls
  namespace: n8n
spec:
  secretName: n8n-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: n8n.southcentralus.cloudapp.azure.com
  dnsNames:
  - n8n.southcentralus.cloudapp.azure.com
