apiVersion: v1
kind: Secret
metadata:
  namespace: n8n
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: n8n_admin
  POSTGRES_PASSWORD: Admin@123
  POSTGRES_DB: n8n
  POSTGRES_NON_ROOT_USER: n8n_user
  POSTGRES_NON_ROOT_PASSWORD: n8n_user@123
  
